### ISSUE TITLE
Відображення розв’язаного кросворда

### ISSUE THREAD

**Issue by danmysak** [ua-dev-front/crossword-master#105]

**Comment by TeksPeks** [comment]
Здається, що у нас зараз не можна дізнатись зі стану - кросворд був згенерований чи розв'язаний. Можливо це і не потрібно, юзер може захотіти подивитись Puzzle view і коли питання були вирішені, просто в цьому випадку спочатку буде вибраний мод Answer, @danmysak @Fybex?

**Comment by danmysak** [comment]
Треба все ж змінити структуру стану, бо треба розуміти, відображати чи ні кнопку «Replace questions».
