### ISSUE TITLE
Зрозуміти, чому прелоадер виглядає гірше, ніж у дизайні, і спробувати це виправити

### ISSUE THREAD

**Issue by danmysak** [ua-dev-front/crossword-master#122]

**Comment by Fybex** [comment]
Колір прелоадера однаковий, але колір клітинок у фігмі інший(#118)

**Comment by danmysak** [comment]
@Fybex Навіть у твоїй версії дизайну (з початковим кольором комірок) прелоадер виглядає добре. На сайті — ні.

**Comment by Fybex** [comment]
> @Fybex Навіть у твоїй версії дизайну (з початковим кольором комірок) прелоадер виглядає добре. На сайті — ні.

Не бачу різниці

Old figma design:
<img width="476" alt="image" src="https://user-images.githubusercontent.com/46112160/201519101-263912ad-7694-4298-846f-f5a4e6a2cb50.png">

Local:
<img width="476" alt="image" src="https://user-images.githubusercontent.com/46112160/201519111-0f907878-154b-448f-be59-0ab5d4a2a1ab.png">

**Comment by Fybex** [comment]
> @Fybex Навіть у твоїй версії дизайну (з початковим кольором комірок) прелоадер виглядає добре. На сайті — ні.

Не бачу різниці

Old figma design:
<img width="476" alt="image" src="https://user-images.githubusercontent.com/46112160/201519101-263912ad-7694-4298-846f-f5a4e6a2cb50.png">

Local:
<img width="476" alt="image" src="https://user-images.githubusercontent.com/46112160/201519111-0f907878-154b-448f-be59-0ab5d4a2a1ab.png">
