### ISSUE TITLE
При генерації і при розв’язуванні кросворда надавати перевагу іменникам

### ISSUE THREAD

**Issue by danmysak** [ua-dev-front/crossword-master#125]

**Comment by Fybex** [comment]
FYI: В запиті до [Datamuse API](https://www.datamuse.com/api/) можна додати **Metadata flag** `p`, який додасть в до кожного слова ключ `tags`, в якому будуть відсортовані частини мови за популярністю. Потім ми у нас на бекенді можемо відсортувати за першою частиною мови слова, але треба визначитися з порядком частин мови для сортування.

**Comment by danmysak** [comment]
Пропоную іменники, прикметники, дієслова, прислівники, все інше.
