### ISSUE TITLE
Проблема через помилку Datamuse API

### ISSUE THREAD

**Issue by danmysak** [ua-dev-front/crossword-master#155]
Приклад: запит
https://api.datamuse.com/words?ml=Small%20flat-bottomed%20fishing%20boat%20suitable%20for%20launching%20from%20a%20beach,%20found%20on%20the%20north-east%20coast%20of%20England%20and%20in%20Scotland.&sp=?????&md=p
повертає
```
{"code":500,"message":"There was an error processing your request. It has been logged (ID ca24ace1352ce4d9)."}
```

При цьому якщо замінити api.datamuse.com на api.onelook.com, запит опрацьовується нормально.

Варто спробувати розібратися, чому оригінальний запит не проходить, а якщо виправити першоджерело не вдасться, то, мабуть, замінити адресу API на api.onelook.com.

**Comment by Fybex** [comment]
Запит не опрацьовується не через різний ліміт символів, перевірив. Не можу знайти інших причин в різниці між ендпоінтами
