### ISSUE TITLE
Помилку коли не вдалося згенерувати кросворд не можна прибрати

### ISSUE THREAD

**Issue by TeksPeks** [ua-dev-front/crossword-master#164]
https://user-images.githubusercontent.com/53875005/207054324-55ce02db-967d-4755-bcc5-72e98fc38f79.mp4

**Comment by Fybex** [comment]
у мене в одного ця помилка тепер завжди при генерації @danmysak, @TeksPeks?

**Comment by danmysak** [comment]
На crossword-master.org теж є.

**Comment by Fybex** [comment]
А яка поведінка запланована @danmysak? Вікно з помилкою повинно зникати через якийсь час чи при натисканні чогось?
