### ISSUE TITLE
Створити демонстраційне відео

### ISSUE THREAD

**Issue by danmysak** [ua-dev-front/crossword-master#170]

**Comment by Fybex** [comment]
https://user-images.githubusercontent.com/46112160/209343414-16918fdf-dbfd-4efa-92f4-4615cb68c9c0.mp4

https://user-images.githubusercontent.com/46112160/209343384-dd08af75-5eeb-4a94-8153-6a8490d3c1d4.mp4

**Comment by Fybex** [comment]
Зробив два варіанти, відрізняються формою таблиці для генерації.

https://user-images.githubusercontent.com/46112160/209452635-3634897b-ebec-49c7-a678-c75b9bcfa507.mp4


https://user-images.githubusercontent.com/46112160/209452638-acf2a2db-278c-4ada-a312-7c8cdbf92daa.mp4

**Comment by danmysak** [comment]
Мені обидва відео подобаються — хіба що режим Replace questions не продемонстровано. Я би вибрав друге.

**Comment by Fybex** [comment]
Чудово, тоді закриваю.
