### ISSUE TITLE
Після генерації кросворду з’являється зайва клітинка

### ISSUE THREAD

**Issue by danmysak** [ua-dev-front/crossword-master#172]
https://user-images.githubusercontent.com/6333637/208491705-161d3d86-b69a-4fff-ab78-7d2078e69337.mp4

**Comment by Fybex** [comment]
@danmysak, хіба це не копія #171

**Comment by danmysak** [comment]
@Fybex Цілком може бути; цілком може не бути. Але ти маєш рацію, вам із @TeksPeks бажано тримати тісний зв’язок із цього приводу.
