### ISSUE TITLE
При фокусуванні/розфукусуванні полів уведення питань колір рамки змінюється миттєво без анімації

### ISSUE THREAD

**Issue by danmysak** [ua-dev-front/crossword-master#174]
Чи ми домовилися так лишити?..

**Comment by TeksPeks** [comment]
Ми це спеціально зробили.
Треба прибрати 
https://github.com/ua-dev-front/crossword-master/blob/896dab7b3a328d47840785668b12dfdb78bf0b1e/frontend/src/components/TextField/index.tsx#L66
щоб анімація була весь час.

**Comment by danmysak** [comment]
А з якою метою, нагадай?

**Comment by TeksPeks** [comment]
https://github.com/ua-dev-front/crossword-master/pull/35#discussion_r950012915
> Мабуть, при фокусуванні/розфокусуванні колір рамки має мінятися миттєво (без анімації) — за аналогією до зміни рамки навколо кнопки і Tabу. Чи можна це малою кров’ю реалізувати без шкоди для анімації при зміні редаговності?

**Comment by danmysak** [comment]
Дякую.
