### ISSUE TITLE
Продумати структуру глобального стану

### ISSUE THREAD

**Issue by danmysak** [ua-dev-front/crossword-master#46]

**Comment by TeksPeks** [comment]
```
mode: Draw | Erase | EnterQuestion | Answer | Puzzle,
table: {
  letter: string, 
  number: number
}[][],
questions: {
	id: number,
	question: string,
	startPosition: {
		row: number,
		column: number,
	},
},
isFetchingFromApi: boolean,
```

**Comment by danmysak** [comment]
@Fybex Цікава твоя думка.

**Comment by Fybex** [comment]
> ```
> mode: Draw | Erase | EnterQuestion | Answer | Puzzle,
> table: {
>   letter: string, 
>   number: number
> }[][],
> questions: {
> 	id: number,
> 	question: string,
> 	startPosition: {
> 		row: number,
> 		column: number,
> 	},
> },
> isFetchingFromApi: boolean,
> ```

1. Тип таблиці, на мою думку, має бути таким:
`({
        letter: string | null;
        number: number | null;
      } | null)[][]`

Також не пам'ятаю чому, але у нас фігурують дві назви: `matrix` на фронтенді та `table` на бекенді(не стосується структури). Можливо треба прийти до однієї назви.

2. Як відрізняти горизонтальні та вертикальні питання?
3. Для чого `isFetchingFromApi` в глобальному стані?

**Comment by TeksPeks** [comment]
> 1. Тип таблиці, на мою думку, має бути таким:
>    `({ letter: string | null; number: number | null; } | null)[][]`

👍 

> 2. Як відрізняти горизонтальні та вертикальні питання?

Переробив структуру `questions` для цього.
> 3. Для чого `isFetchingFromApi` в глобальному стані?

Якщо `Loader` ми можемо використовувати в будь якому компоненті, то мені здається що і `isFetchingFromApi` має бути доступно в будь якому компоненті. Плюс нам може знадобитися "відключити" деякі компоненти поки не прийде відповідь з апі.

Після змін:
```
mode: Draw | Erase | EnterQuestion | Answer | Puzzle,
table: ({ letter: string | null; number: number | null; } | null)[][],
questions: {
	down | across: {
	  id: number,
	  question: string,
	  startPosition: {
		  row: number,
		  column: number,
	  },
	}[][]
},
isFetchingFromApi: boolean,
```

**Comment by danmysak** [comment]
1) EnterQuestion → EnterQuestions
2) Передбачити діалогове вікно підтвердження.

**Comment by TeksPeks** [comment]
Після змін:
```
mode: Draw | Erase | EnterQuestions | Answer | Puzzle | Dialog,
table: {
  letter: string, 
  number: number
}[][],
questions: {
	id: number,
	question: string,
	startPosition: {
		row: number,
		column: number,
	},
},
isFetchingFromApi: boolean,
```

**Comment by danmysak** [comment]
Здається, ти скопіював не той варіант (якраз те, про що говорили на занятті).
Також просто `mode: Dialog` вистачить не всім компонентам, щоб зрозуміти, як відображатися. Потрібно більше інформації.

**Comment by TeksPeks** [comment]
Виправив. Перемістив останній варіант в перший коммент, інші видалив

**Comment by danmysak** [comment]
Пропоную тільки перейменувати:
`showDialog` → `showConfirmation` (щоб було більш конкретно),
`table` → `grid`.

**Comment by danmysak** [comment]
Більше зауважень не маю.

**Comment by danmysak** [comment]
@TeksPeks Мабуть, до `questions` ще варто додати `| null` (у випадку, наприклад, коли маємо `mode: Draw`).

**Comment by TeksPeks** [comment]
А `questions` не може бути просто з пустими масивами `row` і `column`

**Comment by danmysak** [comment]
Ні: список з нуля питань — не те саме, що відсутність списку.

**Comment by TeksPeks** [comment]
Оновив
