### ISSUE TITLE
Відмовитися від слайсів

### ISSUE THREAD

**Issue by danmysak** [ua-dev-front/crossword-master#76]

**Comment by TeksPeks** [comment]
А є якісь причини відмовлятися від слайсів, окрім того, що треба `.general` писати повсюди? Бо це можна виправити не прибираючи слайси якщо в `configureStore` написати
```ts
  reducer: generalSlice.reducer
```
замість
```ts
  reducer: {
    general: generalSlice.reducer,
  },
```

**Comment by Fybex** [comment]
> Крім певної (некритичної) штучності, інших причин не пригадую. Щоб не писати `.general`, здається, було основним аргументом. @Fybex?

Так
