### ISSUE TITLE
Неможливість розв’язати/згенерувати кросворд: оновити типізацію стану

### ISSUE THREAD

**Issue by danmysak** [ua-dev-front/crossword-master#92]

**Comment by TeksPeks** [comment]
```ts
mode: Draw | Erase | EnterQuestions | Answer | Puzzle,
grid: ({ letter: string | null; number: number | null; } | null)[][],
questions: {
	down | across: {
	  id: number,
	  question: string,
	  startPosition: {
		  row: number,
		  column: number,
	  },
	}[]
} | null,
fetchAbortController: AbortController | null,
apiFailed: boolean,
showConfirmation: boolean
```
Додав поле `apiFailed`, яке буде змінюватися на `true`, коли запит повертає `null`, і буде змінюватися на `false`, в тих же випадках коли переривається запит (при натисканні `edit` чи `replace questions`). Коли це поле `true` буде показуватися `Loader` з написом `Couldn't solve this crossword`

**Comment by danmysak** [comment]
@TeksPeks Написів має бути два: наприклад, `We couldn’t solve the crossword :(` та `We were unable to generate the questions :(`. Звідки компонент знатиме, який із цих двох написів виводити?

**Comment by TeksPeks** [comment]
Оновив. В `apiFailed` тепер може зберігатися `Mode.Draw` якщо не вдалося згенерувати питання, і `Mode.EnterQuestions`, якщо не вдалося вирішити.

**Comment by danmysak** [comment]
Цікаве рішення. Гаразд, хай буде.
